<div onload="init()" class="relative">
    <img
    class="object-cover bg-no-repeat max-h-screen min-w-full aspect-video relative"
    src="./src/assets/ZM+SUPERFLY+10+ELITE+FG.png"
    alt="background"
    />
    <div
    class="absolute inset-0 2xl:shadow-customPC md:shadow-custom shadow-customMobile w-full max-h-screen min-w-full"
    >
    <h2
        class="absolute left-4 bottom-4 md:bottom-16 md:left-16 2xl:bottom-36 font-nike text-white-color text-lg md:text-3xl uppercase"
    >
        Vêtement nike fitness
    </h2>
    </div>
</div>
<h2 class="text-3xl font-semibold pt-8 px-8 font-nike">Tout les produits</h2>
<section
    class="grid md:grid-cols-3 grid-cols-1 content-center gap-4 gap-8 shadow-md relative py-12 px-12"
    id="products"
></section>