<div class="flex flex-row mx-32 gap-2 my-4">
  <h1 class="font-semibold text-black-color">Produit :</h1>
  <h2 class="font-medium text-grey-color">{{type}}</h2>
</div>
<div
  class="flex md:flex-row flex-col mx-6 md:mx-20 gap-4 content-center md:justify-start justify-center items-center md:items-start content-center"
>
  <section
    class="sm:flex-row static grid md:grid-cols-2 lg:grid-cols-3 grid-cols-1 gap-4 content-center"
    id="type"
  ></section>
</div>
